import "../styles/globals.css";
import { Provider } from "react-redux";
import store from "../redux/store";
import Head from "next/head";
import Script from "next/script";
import React from "react";
import { checkUser } from "../redux/features/authSlice";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { CustomProvider } from "../components/CustomProvider";

store.dispatch(checkUser());

function MyApp({ Component, pageProps }) {
  const Layout = Component?.Layout ? Component.Layout : React.Fragment;

  return (
    <Provider store={store}>
      <CustomProvider>
        <Layout>
          <Head>
            <title>movie app</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/playicon.ico" />
            <meta
              name="viewport"
              content="width=device-width, initial-scale=1"
            />
          </Head>
          <Script
            src="https://kit.fontawesome.com/2ceb233dee.js"
            crossOrigin="anonymous"
            strategy="lazyOnload"
          />
          <Script src="https://apps.elfsight.com/p/platform.js" defer />

          <Component {...pageProps} />
        </Layout>
      </CustomProvider>
    </Provider>
  );
}

export default MyApp;
